### ISSUE TITLE
Prefer ATF_REQUIRE_EQ to ATF_REQUIRE

### ISSUE THREAD

**Issue by asomers** [shivankgarg98/NFSAuditTestSuite#2]
I see about a hundred different places in the code where you use `ATF_REQUIRE`, `ATF_REQUIRE_MSG`, `ATF_CHECK`, or, `ATF_CHECK_MSG`, followed by a condition that tests equality with `==`.  Instead of doing that, you should use the `_EQ` variants, because they give a better error message on failure.  For example:
```c
ATF_REQUIRE_EQ_MSG(nfs_mount(nfs, url.server, url.path), 0,
    "Failed to mount nfs share");
```
instead of
```c
ATF_REQUIRE_MSG(nfs_mount(nfs, url.server, url.path) == 0,
    "Failed to mount nfs share");
```

**Comment by shivankgarg98** [comment]
Thanks. It's done.
